# -*- coding: utf-8 -*-
"""
/***************************************************************************
 StratigraphicThickness
                                 A QGIS plugin
 prueba
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-27
        copyright            : (C) 2025 by Asier Valenzuela
        email                : asier.valenzuela@ehu.eus
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load StratigraphicThickness class from file StratigraphicThickness.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .stratigraphic_thickness import StratigraphicThickness
    return StratigraphicThickness(iface)
